kakaoRestApiKey: ${KAKAO_REST_API_KEY}

spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver